OpenSource-Communities/pizza-verse

pizza-recipes.md

Adding Pepperoni Pizza Recipe

---

Pizza-history.md

Facts about the first invention of pizza

---

README.md

This PR is responsible for updating the README file to include the correct instructions for how to contribute. 
Previously, the README mentioned folders that were not in existence in the repo. I updated the contribute section so contributions know to edit the `pizza-facts.md` and `pizza-recipes.md` files. 
closes #2

docs: updating contributing section in README

---

pizza-facts.md

**This PR adds a fun fact in the section Pizza Fun Facts in the pizza-facts.md**
- [✔️ ] 🙅 no, because they aren't needed
- [✔️ ] 🙅 no documentation needed

added fun fact to pizza-facts.md

---

style-guide.md

This PR adds a new file called `style-guide.md`. It provides a comprehensive Markdown style guide for formatting PRs in the Pizza Verse project. It also emphasizes the importance of checking for spelling and grammar errors before publishing. 
Fixes #7 
Not yet.

feat: add style guide for creating entries

---

README.md

This PR adds a new step to the README.md file, instructing contributors to follow our `style-guide.md` when adding content to the `pizza-facts.md` or `pizza-recipes.md` files. This will ensure consistency and maintain a unified formatting style throughout the repository.
Fixes #9

feat: hyperlink to style guide

---

pizza-recipes.md

spicy pizza sauce

---

README.md
pizza-facts-&-trivia.md

This PR fixes a hyperlink to pizza-facts.md file in README.md caused a 404 error when accessed to the link due to the repo changed to [pizza-facts-&-trivia.md](https://github.com/open-sauced/pizza-verse/blob/main/pizza-facts-%26-trivia.md). This commit addresses the issue by renaming pizza-facts.md to "pizza-facts-&-trivia.md" for match the correct filename. The issue was identified during read pizza-related content in README.md. Also added another pizza fun facts content.

fix: pizza-facts missing link to markdown file

---

regional-pizza.md

This PR adds a section about New York City pizza to the `regional-pizza.md` file. 
Closes #24 
[Click here to view GIF](https://giphy.com/clips/eternalfamilytv-eternal-family-power-violence-la-pizza-ep-1-Ke8RK9BndpA5L6Ycog)

feat: add information about New York City pizza

---

pizza-facts-&-trivia.md

I have added some pizza related fun facts

---

regional-pizza.md

Added a Japanese-style pizza to the regional menu file.
#32

Added a Japanese-Style pizza

---

pizza-recipes.md

I have added remaining pizza recipes to the table of contents.
- [☑ ] 🐛 Bug Fix
#41 this is the issue number

Added remaining pizza recipes to the table of contents

---

pizza-facts-&-trivia.md

Added pizza trivia question number 4.
Closes #36  
Nope.

feat: Added trivia questions #4

---

pizza-facts-&-trivia.md

Add a fact about pizza
Relates to #36

add sunny fact about pizza

---

README.md
pizza-facts-&-trivia.md
pizza-recipes.md
regional-pizza.md
style-guide.md

This PR updates the rules and steps to contribute in the README with details as follow:
- Added a rule for accepting only one added item per contributor.
- Updated the steps to contribute.
- Added a step to create a new branch.
- Improved the wordings in step 4.
- Added links for the GitHub and git commands.
This PR also updates:
- The rule to use dash (-) instead of asterisks (*) for unordered list in the `style-guide.md`.
- The unordered list in `pizza-facts-&-trivia.md` and `regional-pizza.md` by replacing asterisks with dashes.
Relates to #31

Update rules and steps to contribute in the README

---

README.md

This PR adds a "Keeping Branch Up to Date and Resolving Merge Conflicts" section to the README. The purpose is to walkthrough our contributors whenever they face merge conflicts.
Closes #31

Add a Resolving Merge Conflicts section to the README

---

pizza-facts-&-trivia.md

Added a new fact to the pizza-facts-&-trivia.md file
#36

Add new pizza fact about toppings

---

pizza-facts-&-trivia.md

This PR adds a new pizza fact to the list.
Relates to #36

feat: Add Pizza fact.

---

pizza-facts-&-trivia.md

This PR adds the feature/add-pizza-trivia in **Pizza Trivia** list.
Related to #36
NO

Feature: New Pizza Trivia Added

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds a PR template in the `.github` folder and adjusts the content with what are needed in this repo.
Closes #61

feature: Add a PR template 

---

pizza-recipes.md

This PR adds Zanzibar Pizza to pizza-recipes.md
Relates to #32 and #35

feat: Add Zanzibar pizza

---

pizza-facts-&-trivia.md

This PR adds the number of US pizza restaurants into pizza-facts-&-trivia.md.
Relates to #36

docs: Adding fact about number of US pizza restaurants to pizza-facts-&-trivia.md

---

pizza-facts-&-trivia.md

This PR adds pizza trivia number 6
Relates to [#36](https://github.com/open-sauced/pizza-verse/issues/36)

New pizza trivia added

---

pizza-facts-&-trivia.md

This PR adds a pizza fact.
Relates to https://github.com/open-sauced/pizza-verse/issues/36

Add a pizza fact

---

style-guide.md

Style-guide.md update.
Corrected the grammar of a sentence in the Links section, and fixed a formatting issue in the Notes section.
Fixes #70

fix: Correct Grammar

---

pizza-facts-&-trivia.md

This PR adds a pizza trivia.
Relates to #36

Add a pizza trivia (pizza patatine)

---

.github/workflows/compliance.yml

This PR adds the compliance workflow to check if a PR is following our standard and convention. I applied the same workflow as in the [docs repo](https://github.com/open-sauced/docs/blob/main/.github/workflows/compliance.yml).
Closes #89

feat: add compliance workflow

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
world-traditional-food.md

This PR adds a new format of contribution, which is "Traditional Food Around the World". The changes in this PR inlude:
- Added a new file called `world-traditional-foods.md`.
- Added an example in the file.
- Update the README to include this new format.
Closes #84

feat: Add traditional food around the world as a new format of contribution

---

pizza-facts-&-trivia.md

This PR will add a fun fact about pizzas in Kenya in the pizza-facts-&-trivia.md
- [ x ] ☝️ Add a pizza fact or trivia
Relates to #87

feat: Add a fact about Kenya's pizza

---

.github/workflows/compliance.yml

This PR fixes the issue reference check by updating the `compliance.yml` file with below changes:
- Use the code from [compliance.yml at hot repo](https://github.com/open-sauced/hot/blob/beta/.github/workflows/compliance.yml).
- Add `body-regex: '(fix(es|ed)?|resolve(s|d)?|close(s|d)?|related to|relates to|relate to) ((https:\/\/github.com\/[a-zA-Z0-9-_]+\/[a-zA-Z0-9-_]+\/issues\/d*[1-9]d*?)|(#d*[1-9]d*?))'` to add keywords "Relate to", "Relates to", and "Related to" to the default ones.
https://github.com/open-sauced/pizza-verse/assets/45172775/7a504ef0-1252-420d-b10d-8f0f9b78efd8
Fixes #93

fix: compliance action to include "relates to" and "related to" keywords when checking related issue

---

pizza-facts-&-trivia.md

The 'Pizza Fun Facts' section of the 'pizza-facts-&-trivia.md' file in the 'pizza-verse' repository has been updated with new additions
Relates to #36

feat: New Pizza Fun Facts

---

pizza-facts-&-trivia.md

Added a pizza fact into the repo's fact and trivia markdown file
Relates to #36

feat: Added Pizza Fact

---

.github/CODEOWNERS

This PR changes the code owners from community to docs.
Fixes #104

fix: change code owners from community to docs

---

pizza-facts-&-trivia.md

- [✔ ] ☝️ Add a pizza fact or trivia
Relates to #110 
- [ ✔] 🙅 no documentation needed

feat: Added a fun fact about pizza in Egypt

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
LICENSE.txt
README.md
package.json
style-guide.md

This PR updates contents and links to adjust with the current home of the project.
Closes #114

docs: Update docs
